# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: true
  devices: auto
  num_nodes: 1
  # precision: bf16
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: /home/xshadow/terratorch/logs
      name: dofav2_burnscars_uper
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 20

  max_epochs: 50
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: /home/xshadow/terratorch/logs

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 4
    dataset_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    no_data_replace: 0
    no_label_replace: -1
    train_data_root: /home/xshadow/terratorch/data/burnscars/training
    train_label_data_root: /home/xshadow/terratorch/data/burnscars/training
    val_data_root: /home/xshadow/terratorch/data/burnscars/validation
    val_label_data_root: /home/xshadow/terratorch/data/burnscars/validation
    test_data_root: /home/xshadow/terratorch/data/burnscars/validation
    test_label_data_root: /home/xshadow/terratorch/data/burnscars/validation
    img_grep: "*_merged.tif"
    label_grep: "*.mask.tif"
    means:
      - 0.033349706741586264
      - 0.05701185520536176
      - 0.05889748132001316
      - 0.2323245113436119
      - 0.1972854853760658
      - 0.11944914225186566
    stds:
      - 0.02269135568823774
      - 0.026807560223070237
      - 0.04004109844362779
      - 0.07791732423672691
      - 0.08708738838140137
      - 0.07241979477437814
    num_classes: 2
    train_transform:
      - class_path: albumentations.RandomCrop
        init_args:
            height: 512
            width: 512
      - class_path: albumentations.HorizontalFlip
        init_args:
            p: 0.5
      - class_path: ToTensorV2
    val_transform:
      - class_path: albumentations.RandomCrop
        init_args:
            height: 512
            width: 512
      - class_path: ToTensorV2
    test_transform:
      - class_path: albumentations.CenterCrop
        init_args:
            height: 512
            width: 512
      - class_path: ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: UperNetDecoder
      backbone_pretrained: True
      backbone: dofav2_large_patch14_224
      backbone_ckpt_data: https://hf.co/earthflow/DOFA/resolve/main/dofav2_vit_large_e150.pth
      #backbone_ckpt_data: https://hf.co/earthflow/DOFA/resolve/main/dinov2_large_patch14_224.pth
      backbone_convert_patch_14_to_16: False
      backbone_img_size: 512
      # decoder_scale_modules: True
      # decoder_in_channels: 1024
      decoder_channels: 256
      # backbone_in_channels: 6
      backbone_model_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2

      backbone_out_indices:
          - 5
          - 11
          - 17
          - 23
      # num_frames: 1
      num_classes: 2
      head_dropout: 0.1
      head_channel_list:
        - 256
      necks:
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
    loss: dice
    
    ignore_index: -1
    class_weights:
      - 0.3
      - 0.7
    freeze_backbone: false
    freeze_decoder: false
    model_factory: EncoderDecoderFactory
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 6.e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
