# lightning.pytorch==2.1.1
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: true
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
  max_epochs: 100
  log_every_n_steps: 5
  default_root_dir: output/sen1floods11/

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 8
    num_workers: 2
    constant_scale: 0.0001
    dataset_bands:
      - COASTAL_AEROSOL
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - CIRRUS
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0

    train_data_root: sen1floods11_v1.1/data/S2L1CHand
    train_label_data_root: sen1floods11_v1.1/data/LabelHand
    val_data_root: sen1floods11_v1.1/data/S2L1CHand
    val_label_data_root: sen1floods11_v1.1/data/LabelHand
    test_data_root: sen1floods11_v1.1/data/S2L1CHand
    test_label_data_root: sen1floods11_v1.1/data/LabelHand
    train_split: sen1floods11_v1.1/splits/flood_train_data.txt
    val_split: sen1floods11_v1.1/splits/flood_valid_data.txt
    test_split: sen1floods11_v1.1/splits/flood_test_data.txt

    img_grep: "*_S2Hand.tif"
    label_grep: "*_LabelHand.tif"
    no_label_replace: -1
    no_data_replace: 0
    means:
      - 0.11076498225107874
      - 0.13456047562676646
      - 0.12477149645635542
      - 0.3248933937526503
      - 0.23118412840904512
      - 0.15624583324071273
    stds:
      - 0.15469174852002912
      - 0.13070592427323752
      - 0.12786689586224442
      - 0.13925781946803198
      - 0.11303782829438778
      - 0.10207461132314981
    num_classes: 2
    drop_last: True
    train_transform:
      - class_path: albumentations.D4
      - class_path: albumentations.pytorch.ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_v2_300_tl
      backbone_pretrained: true
      backbone_img_size: 512
      backbone_coords_encoding: []
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      necks:
        - name: SelectIndices
          indices: [5, 11, 17, 23]
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
      decoder: UNetDecoder
      decoder_channels: [512, 256, 128, 64]
      head_dropout: 0.1
      num_classes: 2
    loss: dice
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.1
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    factor: 0.5
    patience: 5

