# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: true

  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: /home/xshadow/terratorch/logs/od_vhr10_clayv1_hpo/
      name: od_vhr10_clayv1_lr_0.0003_wd_0.01_warmup_2_e40
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
          mode: max
          monitor: val_map
          filename: best-{epoch:02d}
  max_epochs: 40
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: /home/xshadow/terratorch/logs/
data:
  class_path: terratorch.datamodules.mVHR10DataModule
  init_args:
    root: /home/xshadow/terratorch/data/VHR10/
    download: true
    batch_size: 2
    num_workers: 4
    pad: false
    image_size: 896

model:
  class_path: terratorch.tasks.ObjectDetectionTask
  init_args:
    model_factory: ObjectDetectionModelFactory
    model_args:
      framework: mask-rcnn
      backbone: clay_v1_base  
      backbone_pretrained: true
      num_classes: 12
      backbone_img_size: 896
      framework_min_size: 896
      framework_max_size: 896
      backbone_bands:
        - RED
        - GREEN
        - BLUE
      necks:
        - name: SelectIndices
          indices: [2, 5, 8, 11]
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
        - name: FeaturePyramidNetworkNeck
        
    freeze_backbone: false
    freeze_decoder: false
    class_names:
      - Background
      - Airplane
      - Ships
      - Storage tank
      - Baseball diamond
      - Tennis court
      - Basketball court
      - Ground track field
      - Harbor
      - Bridge
      - Vehicle

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0003
    weight_decay: 0.01

lr_scheduler:
  class_path: torch.optim.lr_scheduler.OneCycleLR
  init_args:
    max_lr: 0.0003
    total_steps: 40
    pct_start: 0.05
    anneal_strategy: "cos"
    div_factor: 10.0
    final_div_factor: 1000.0
